// Data default portfolio - diisi dari Admin Dashboard
export const defaultData = {
  beranda: {
    nama: "Ulis Leuwol",
    gelar: "IT Professional & Data Administrator",
    deskripsi: "Mencari solusi yang efisien, praktis, dan bermanfaat melalui teknologi dan pengelolaan data yang baik.",
    lokasi: "Haria, Saparua",
    telepon: "0852 8035 7433",
    email: "ulissleksmart@gmail.com",
    inisial: "UL",
    subGelar: "S1 Teknik Informatika",
    ipk: "3.99",
  },
  tentang: {
    teks: "Saya adalah pribadi yang memiliki semangat belajar tinggi, terbuka terhadap hal baru, dan selalu berusaha memberikan hasil terbaik dalam setiap pekerjaan. Saya menyukai tantangan yang dapat mengembangkan kemampuan diri serta memiliki komitmen kuat terhadap tanggung jawab dan profesionalitas.",
    moto: "\"Kalau bisa dipermudah, kenapa harus dipersulit?\"",
    prinsip: "Prinsip saya dalam bekerja adalah mencari solusi yang efisien, praktis, dan bermanfaat.",
  },
  pengalaman: [
    {
      id: 1,
      periode: "24 Nov 2025 - 24 Mei 2026",
      jabatan: "Pengelola Fasilitas Umum",
      institusi: "MagangHub Kemnaker - Lapas Kelas III Saparua",
      deskripsi: "",
      poin: [
        "Menyiapkan sarana pendukung kegiatan umum seperti ruang rapat, kendaraan, dan logistik.",
        "Memantau penggunaan fasilitas agar efisien.",
        "Mengatur perawatan rutin fasilitas umum.",
        "Membantu kebutuhan operasional kantor.",
      ],
      warna: "indigo",
    },
    {
      id: 2,
      periode: "Januari 2025 - Sekarang",
      jabatan: "Admin Sektor - MSIPT & Website Gereja",
      institusi: "Gereja Protestan Maluku - Halong Anugerah",
      deskripsi: "Bertanggung jawab dalam pengelolaan data jemaat melalui sistem informasi pelayanan terpadu berbasis web.",
      poin: [
        "Pembaruan data jemaat yang telah ada serta penambahan data baru secara berkala.",
        "Memastikan akurasi, kelengkapan, dan keterkinian informasi.",
        "Melaksanakan validasi data dan koordinasi lintas sektor.",
      ],
      warna: "blue",
    },
    {
      id: 3,
      periode: "Oktober 2021 - Sekarang",
      jabatan: "Freelance Admin Data Processor",
      institusi: "KSOP Kelas I Ambon (Remote)",
      deskripsi: "Dipercaya secara pribadi untuk melanjutkan tugas pengolahan data dan penyusunan laporan bulanan secara remote berdasarkan kinerja saat KKP.",
      poin: [
        "Mengunduh data dari website SPS Inapornet Kemenhub.",
        "Mengolah data aktivitas bongkar muat barang berbahaya & pengisian bahan bakar kapal.",
        "Menginput data ke MS Excel dan menyusun laporan bulanan.",
      ],
      warna: "teal",
    },
    {
      id: 4,
      periode: "Juli 2021 - September 2021",
      jabatan: "Administrasi - KKP",
      institusi: "KSOP Kelas I Ambon",
      deskripsi: "Kuliah Kerja Praktek (KKP). Bertugas mengambil data dari website SPS Inapornet milik Kementerian Perhubungan, mencetak, serta menginput data ke dalam Excel untuk disusun menjadi laporan bulanan.",
      poin: [],
      warna: "slate",
    },
  ],
  pencapaian: [
    {
      id: 1,
      tahun: "Tahun 2025",
      judul: "Lulus BEKUP Create: Upskilling Bootcamp 2025",
      deskripsi: "Menyelesaikan Upskilling Bootcamp BEKUP Create 2025 yang diinisiasi oleh Badan Ekonomi Kreatif (BEKRAF) dan Dicoding Indonesia. Mempelajari pengembangan aplikasi menggunakan Flutter serta mengasah soft skill penting seperti personal productivity, critical thinking, dan effective communication.",
      proyekJudul: "Proyek Akhir: \"Jejak Cerita Rakyat\"",
      proyekDeskripsi: "Aplikasi edukatif berbasis Flutter yang bertujuan mengenalkan kembali cerita rakyat Indonesia kepada anak-anak. Dilengkapi dengan fitur text-to-speech yang ramah disabilitas.",
      tags: ["Flutter", "Mobile Development", "Text-to-Speech API", "Team Collaboration"],
    },
  ],
  pendidikan: {
    formal: [
      {
        id: 1,
        jenjang: "S1 Teknik Informatika",
        institusi: "Institut Teknologi dan Bisnis STIKOM Ambon",
        periode: "2020 - 2025",
        nilai: "IPK: 3.99",
        warna: "blue",
      },
      {
        id: 2,
        jenjang: "SMA Nambuasa Tulehu",
        institusi: "Jurusan Ilmu Pengetahuan Alam (IPA)",
        periode: "2016 - 2018",
        nilai: "Nilai: 90",
        warna: "slate",
      },
    ],
    sertifikasi: [
      { id: 1, judul: "Belajar Penggunaan Generative AI", tanggal: "Sep 2025", kategori: "dicoding" },
      { id: 2, judul: "Belajar Dasar AI", tanggal: "Sep 2025 - Sep 2028", kategori: "dicoding" },
      { id: 3, judul: "AI Praktis untuk Produktivitas", tanggal: "Mei 2025 - Mei 2028", kategori: "dicoding" },
      { id: 4, judul: "Advance Microsoft Excel", tanggal: "Juni 2022", kategori: "pelatihan", institusi: "ITB STIKOM Ambon" },
      { id: 5, judul: "Merakit Dan Instalasi PC", tanggal: "Desember 2021", kategori: "pelatihan", institusi: "ITB STIKOM Ambon" },
    ],
  },
  keterampilan: [
    "Problem Solving",
    "Microsoft PowerPoint",
    "Microsoft Word",
    "Menunjukkan komitmen",
    "Data Entry",
    "Installation System Operasi Windows",
    "Installation Software",
    "Microsoft Excel",
    "Menggunakan Komputer",
    "Microsoft Office",
  ],
};
